
-- Insert into CATEGORY_TABLE
INSERT INTO CATEGORY_TABLE (CATEGORYID, CATEGORYNAME) VALUES (CATEGORY_TABLE_SEQ.nextval, 'root');
INSERT INTO CATEGORY_TABLE (CATEGORYID, CATEGORYNAME, PARENTID) VALUES (CATEGORY_TABLE_SEQ.nextval, 'Electronics', 0);
INSERT INTO CATEGORY_TABLE (CATEGORYID, CATEGORYNAME, PARENTID) VALUES (CATEGORY_TABLE_SEQ.nextval, 'Laptops', 1);
INSERT INTO CATEGORY_TABLE (CATEGORYID, CATEGORYNAME, PARENTID) VALUES (CATEGORY_TABLE_SEQ.nextval, 'Smartphones', 1);
INSERT INTO CATEGORY_TABLE (CATEGORYID, CATEGORYNAME, PARENTID) VALUES (CATEGORY_TABLE_SEQ.nextval, 'Gaming Laptops', 2);
INSERT INTO CATEGORY_TABLE (CATEGORYID, CATEGORYNAME, PARENTID) VALUES (CATEGORY_TABLE_SEQ.nextval, 'Android Phones', 3);
INSERT INTO CATEGORY_TABLE (CATEGORYID, CATEGORYNAME, PARENTID) VALUES (CATEGORY_TABLE_SEQ.nextval, 'iOS Phones', 3);
COMMIT;

-- Insert into PRODUCT_TABLE
INSERT INTO PRODUCT_TABLE (PRODUCTID, PRODUCTNAME) VALUES (PRODUCT_TABLE_SEQ.nextval, 'ASUS ROG Strix');
INSERT INTO PRODUCT_TABLE (PRODUCTID, PRODUCTNAME) VALUES (PRODUCT_TABLE_SEQ.nextval, 'S21');
COMMIT;

-- Link a product with a category in CATEGORY_TABLE_PRODUCT_TABLE
INSERT INTO CATEGORY_TABLE_PRODUCT_TABLE (CATEGORY_CATEGORYID, PRODUCTS_PRODUCTID) VALUES (4, 1);
INSERT INTO CATEGORY_TABLE_PRODUCT_TABLE (CATEGORY_CATEGORYID, PRODUCTS_PRODUCTID) VALUES (5, 2);
COMMIT;

-- SELECT p.PRODUCTID, p.PRODUCTNAME, c.CATEGORYID FROM PRODUCT_TABLE p, CATEGORY_TABLE_PRODUCT_TABLE cp, CATEGORY_TABLE c WHERE cp.PRODUCTS_PRODUCTID = p.PRODUCTID and c.CATEGORYID = cp.CATEGORY_CATEGORYID;

-- WITH RECURSIVE (CATEGORYID, CATEGORYNAME, PARENTID) AS (
--   SELECT CATEGORYID, CATEGORYNAME, PARENTID
--   FROM CATEGORY_TABLE
--   WHERE CATEGORYID = 4  -- Starting category_id
--
--   UNION ALL
--
--   SELECT c.CATEGORYID, c.CATEGORYNAME, c.PARENTID
--   FROM CATEGORY_TABLE c
--   JOIN RECURSIVE cp ON c.CATEGORYID = cp.PARENTID
-- )
-- SELECT CATEGORYID, CATEGORYNAME
-- FROM RECURSIVE;


